name: mirror
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to school repo
        run: |
          git remote add school https://x-access-token:${{ secrets.SCHOOL }}@github.com:EpitechMscProPromo2027/T-DEV-700-project-PAR_36.git
          git push school main
